name: CI

on: [push]

jobs:
  run:    
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    name: Test on PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Install dependencies
      run: composer install --ignore-platform-reqs
    - name: Run tests
      run: composer ci
